stages:
    - build
    - deploy

build react:
    image: node:16-alpine
    stage: build
    script:
        - cd frontend/
        - pwd
        - yarn install
        - yarn build
    artifacts:
        paths: 
            - frontend/build

