stages:
    - build
    - deploy

build react:
    image: node:16-alpine
    stage: build
    script:
        - cd frontend/
        - yarn install
        - yarn build
    artifacts:
        paths: 
            - build

deploy to S3:
    image: 
        name: amazon/aws-cli:2.4.11
        entrypoint: [""]
    script:
        - aws s3 sync build s3://$AWS_S3_BUCKET --delete
        - cdk deploy

